# Log10x Status Page Configuration
# Powered by Upptime: https://upptime.js.org

owner: log-10x
repo: status

# Service monitors
sites:
  - name: Console
    url: https://console.log10x.com
    maxResponseTime: 5000

  - name: API
    url: https://api.log10x.com/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Auth
    url: https://auth.log10x.com/.well-known/openid-configuration
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

# Status page customization
status-website:
  baseUrl: /
  name: Log10x Status
  introTitle: "**Log10x** System Status"
  introMessage: Current status of Log10x services.
  theme: dark
  navbar:
    - title: Console
      href: https://console.log10x.com
    - title: Documentation
      href: https://doc.log10x.com
  css: |
    @import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap');
    :root {
      --background-primary: #01080f;
      --background-secondary: #101519;
      --background-tertiary: #151c22;
      --text-primary: #ffffff;
      --text-secondary: #b3b5b7;
      --accent-green: #00ff41;
      --accent-cyan: #00d9ff;
      --brand-1: #5f6f83;
      --brand-2: #48535f;
      --error: #8b0000;
    }
    * { font-family: 'Ubuntu', sans-serif !important; }
    body { background: var(--background-primary) !important; }
    .dark { background: var(--background-primary) !important; }
    h1, h2, h3 { color: var(--text-primary) !important; }
    h1 strong { color: var(--accent-green) !important; }
    .status-up { background: linear-gradient(135deg, #00ff41 0%, #00d9ff 100%) !important; }
    .status-down { background: linear-gradient(135deg, #ff0066 0%, #8b0000 100%) !important; }
    nav { background: var(--background-secondary) !important; border-bottom: 1px solid var(--brand-2) !important; }
    a { color: var(--accent-cyan) !important; }
    a:hover { color: var(--accent-green) !important; }
    .card, article { background: var(--background-secondary) !important; border: 1px solid var(--brand-2) !important; border-radius: 8px !important; }
    footer { background: var(--background-secondary) !important; border-top: 1px solid var(--brand-2) !important; }

# Check frequency (in minutes)
workflowSchedule:
  graphs: "0 0 * * *"        # Daily graphs update
  responseTime: "0 23 * * *" # Daily response time check
  staticSite: "0 1 * * *"    # Daily static site rebuild
  summary: "0 0 * * *"       # Daily summary
  updateTemplate: "0 0 * * *"
  uptime: "*/5 * * * *"      # Check every 5 minutes

# Incident management
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  incidentReport: "Incident Report for {DATE}"
  pastIncidents: Past Incidents
  scheduledMaintenance: Scheduled Maintenance
  footer: "Powered by [Upptime](https://upptime.js.org)"

# GitHub Pages configuration
cname: status.log10x.com

# Commit messages
commitMessages:
  readmeContent: ":robot: Update summary in README"
  summaryJson: ":card_file_box: Update summary in JSON"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_TIME ms)"
  graphsUpdate: ":bento: Update graphs"
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@log10x.com"
