# Log10x Status Page Configuration
# Powered by Upptime: https://upptime.js.org

owner: log-10x
repo: status

# Service monitors
sites:
  - name: Console
    url: https://console.log10x.com
    maxResponseTime: 5000

  - name: API
    url: https://api.log10x.com/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Auth
    url: https://auth.log10x.com/.well-known/openid-configuration
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

# Status page customization
status-website:
  baseUrl: /
  name: Log10x Status
  introTitle: "**Log10x** Status"
  introMessage: Real-time system health and uptime.
  theme: dark
  navbar:
    - title: Console
      href: https://console.log10x.com
    - title: Documentation
      href: https://doc.log10x.com
  css: |
    @import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap');
    * { font-family: 'Ubuntu', -apple-system, BlinkMacSystemFont, sans-serif !important; -webkit-font-smoothing: antialiased; }
    body, .dark { background: #01080f !important; }
    main { max-width: 800px; margin: 0 auto; padding: 60px 24px; }
    h1 { font-weight: 300 !important; font-size: 2.5rem !important; letter-spacing: -0.5px; margin-bottom: 8px !important; }
    h1 strong { font-weight: 500 !important; color: #fff !important; }
    h2 { font-weight: 400 !important; font-size: 1.1rem !important; color: rgba(255,255,255,0.6) !important; margin-bottom: 40px !important; }
    h3 { font-weight: 500 !important; font-size: 0.9rem !important; text-transform: uppercase; letter-spacing: 1px; color: rgba(255,255,255,0.5) !important; margin: 48px 0 20px !important; }
    nav { background: rgba(1,8,15,0.95) !important; backdrop-filter: blur(10px); border-bottom: 1px solid rgba(255,255,255,0.08) !important; padding: 16px 24px !important; }
    nav a { color: rgba(255,255,255,0.7) !important; font-weight: 400 !important; font-size: 0.9rem !important; text-decoration: none !important; transition: color 0.2s; }
    nav a:hover { color: #fff !important; }
    a { color: rgba(255,255,255,0.8) !important; text-decoration: none; transition: color 0.2s; }
    a:hover { color: #fff !important; }
    article, .card, div[class*="status"] { background: rgba(255,255,255,0.03) !important; border: 1px solid rgba(255,255,255,0.08) !important; border-radius: 12px !important; padding: 20px 24px !important; margin-bottom: 12px !important; transition: border-color 0.2s, background 0.2s; }
    article:hover, .card:hover { background: rgba(255,255,255,0.05) !important; border-color: rgba(255,255,255,0.12) !important; }
    .status-up, [class*="operational"], [class*="success"] { background: rgba(34,197,94,0.1) !important; border-color: rgba(34,197,94,0.2) !important; }
    .status-down, [class*="down"], [class*="error"] { background: rgba(239,68,68,0.1) !important; border-color: rgba(239,68,68,0.2) !important; }
    footer { background: transparent !important; border-top: 1px solid rgba(255,255,255,0.08) !important; padding: 40px 24px !important; margin-top: 60px; }
    footer, footer * { color: rgba(255,255,255,0.4) !important; font-size: 0.85rem !important; }
    p { color: rgba(255,255,255,0.7); line-height: 1.6; }
    svg, img[src*="logo"] { opacity: 0.9; }
    ::selection { background: rgba(255,255,255,0.2); }

# Check frequency (in minutes)
workflowSchedule:
  graphs: "0 0 * * *"        # Daily graphs update
  responseTime: "0 23 * * *" # Daily response time check
  staticSite: "0 1 * * *"    # Daily static site rebuild
  summary: "0 0 * * *"       # Daily summary
  updateTemplate: "0 0 * * *"
  uptime: "*/5 * * * *"      # Check every 5 minutes

# Incident management
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  incidentReport: "Incident Report for {DATE}"
  pastIncidents: Past Incidents
  scheduledMaintenance: Scheduled Maintenance
  footer: "Powered by [Upptime](https://upptime.js.org)"

# GitHub Pages configuration
cname: status.log10x.com

# Commit messages
commitMessages:
  readmeContent: ":robot: Update summary in README"
  summaryJson: ":card_file_box: Update summary in JSON"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_TIME ms)"
  graphsUpdate: ":bento: Update graphs"
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@log10x.com"
