# Log10x Status Page Configuration
# Powered by Upptime: https://upptime.js.org

owner: log-10x
repo: status

# Service monitors
sites:
  - name: Console
    url: https://console.log10x.com
    maxResponseTime: 5000

  - name: API
    url: https://api.log10x.com/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Auth
    url: https://auth.log10x.com/.well-known/openid-configuration
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

# Status page customization
status-website:
  baseUrl: /
  name: Log10x Status
  logoUrl: https://log10x.com/images/Logo.png
  introTitle: "System Status"
  introMessage: Real-time health monitoring for Log10x services.
  theme: dark
  navbar:
    - title: Console
      href: https://console.log10x.com
    - title: Documentation
      href: https://doc.log10x.com
  css: |
    @import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap');
    :root { --bg: #01080f; --bg2: #101519; --bg3: #151c22; --border: #272d33; --text: #cacaca; --text2: #91919c; --white: #fff; --green: #4ade80; }
    * { font-family: Ubuntu, Helvetica, sans-serif !important; -webkit-font-smoothing: antialiased; box-sizing: border-box; }
    body, .dark { background: var(--bg) !important; color: var(--text) !important; }
    main { max-width: 720px; margin: 0 auto; padding: 48px 24px; }
    h1 { font-weight: 700 !important; font-size: 1.5rem !important; color: var(--white) !important; margin: 0 0 4px !important; letter-spacing: 0.5px; }
    h1 strong { font-weight: 700 !important; color: var(--green) !important; }
    h2, .intro { font-size: 0.95rem !important; color: var(--text2) !important; font-weight: 400 !important; margin: 0 0 32px !important; }
    h3 { font-size: 0.75rem !important; font-weight: 500 !important; color: var(--text2) !important; text-transform: uppercase; letter-spacing: 0.5px; margin: 40px 0 16px !important; }
    nav { background: var(--bg2) !important; border-bottom: 1px solid var(--border) !important; padding: 12px 24px !important; }
    nav a { color: var(--text) !important; font-size: 0.875rem !important; text-decoration: none !important; }
    nav a:hover { color: var(--white) !important; }
    a { color: var(--text) !important; text-decoration: none !important; }
    a:hover { color: var(--white) !important; }
    article, .card { background: var(--bg2) !important; border: 1px solid var(--border) !important; border-radius: 8px !important; padding: 16px 20px !important; margin-bottom: 8px !important; }
    article:hover, .card:hover { border-color: #3a4149 !important; }
    div[class*="status"], section { background: transparent !important; border: none !important; }
    footer { background: transparent !important; border-top: 1px solid var(--border) !important; padding: 32px 0 !important; margin-top: 48px; }
    footer, footer * { color: var(--text2) !important; font-size: 0.8rem !important; }
    p { color: var(--text); font-size: 0.9rem; line-height: 1.5; margin: 4px 0; }
    .status-up, [class*="operational"], article.up { background: var(--bg2) !important; border: 1px solid var(--border) !important; }
    .status-down, article.down { background: rgba(239, 68, 68, 0.05) !important; border: 1px solid rgba(239, 68, 68, 0.3) !important; }
    [class*="degraded"] { background: rgba(245, 158, 11, 0.05) !important; border: 1px solid rgba(245, 158, 11, 0.3) !important; }
    .uptime-bar, .response-time { opacity: 0.7; }
    svg { max-width: 100%; }
    [class*="status"] span, .status-text { font-size: 0.8rem; }
    article *, .card * { border-left: none !important; }

# Check frequency (in minutes)
workflowSchedule:
  graphs: "0 0 * * *"        # Daily graphs update
  responseTime: "0 23 * * *" # Daily response time check
  staticSite: "0 1 * * *"    # Daily static site rebuild
  summary: "0 0 * * *"       # Daily summary
  updateTemplate: "0 0 * * *"
  uptime: "*/5 * * * *"      # Check every 5 minutes

# Incident management
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  incidentReport: "Incident Report for {DATE}"
  pastIncidents: Past Incidents
  scheduledMaintenance: Scheduled Maintenance
  footer: "Powered by [Upptime](https://upptime.js.org)"

# GitHub Pages configuration
cname: status.log10x.com

# Commit messages
commitMessages:
  readmeContent: ":robot: Update summary in README"
  summaryJson: ":card_file_box: Update summary in JSON"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_TIME ms)"
  graphsUpdate: ":bento: Update graphs"
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@log10x.com"
