# Log10x Status Page Configuration
# Powered by Upptime: https://upptime.js.org

owner: log-10x
repo: status

# Service monitors
sites:
  - name: Console
    url: https://console.log10x.com
    maxResponseTime: 5000

  - name: API
    url: https://api.log10x.com/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Auth
    url: https://auth.log10x.com/.well-known/openid-configuration
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

# Status page customization
status-website:
  baseUrl: /
  name: Log10x Status
  introTitle: "**Log10x** System Status"
  introMessage: Current status of Log10x services.
  theme: dark
  navbar:
    - title: Console
      href: https://console.log10x.com
    - title: Documentation
      href: https://doc.log10x.com

# Check frequency (in minutes)
workflowSchedule:
  graphs: "0 0 * * *"        # Daily graphs update
  responseTime: "0 23 * * *" # Daily response time check
  staticSite: "0 1 * * *"    # Daily static site rebuild
  summary: "0 0 * * *"       # Daily summary
  updateTemplate: "0 0 * * *"
  uptime: "*/5 * * * *"      # Check every 5 minutes

# Incident management
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  incidentReport: "Incident Report for {DATE}"
  pastIncidents: Past Incidents
  scheduledMaintenance: Scheduled Maintenance
  footer: "Powered by [Upptime](https://upptime.js.org)"

# GitHub Pages configuration
cname: status.log10x.com

# Commit messages
commitMessages:
  readmeContent: ":robot: Update summary in README"
  summaryJson: ":card_file_box: Update summary in JSON"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_TIME ms)"
  graphsUpdate: ":bento: Update graphs"
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@log10x.com"
